global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: nginx-prometheus-exporter

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']
